version: "3.9"

services:
  backend:
    build: ./trading-dashboard/backend
    container_name: tradex-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-3600000}

  frontend:
    build: ./frontend/tradingfrontend
    container_name: tradex-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
